/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OrderSuccessRouteImport } from './routes/order-success'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShopIndexRouteImport } from './routes/shop.index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as CheckoutSlugRouteImport } from './routes/checkout.$slug'
import { Route as AppWhatsappRouteImport } from './routes/app/whatsapp'
import { Route as AppSettingsRouteImport } from './routes/app/settings'
import { Route as AppProvidersRouteImport } from './routes/app/providers'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppOrdersRouteImport } from './routes/app/orders'
import { Route as AppOnboardingRouteImport } from './routes/app/onboarding'
import { Route as AppFacebookRouteImport } from './routes/app/facebook'
import { Route as AppEcommerceRouteImport } from './routes/app/ecommerce'
import { Route as AppDashboardRouteImport } from './routes/app/dashboard'
import { Route as AppChatsRouteImport } from './routes/app/chats'
import { Route as AppBrandMemoryRouteImport } from './routes/app/brand-memory'
import { Route as AppAiSettingsRouteImport } from './routes/app/ai-settings'
import { Route as AdminTenantsRouteImport } from './routes/admin/tenants'
import { Route as AdminSystemHealthRouteImport } from './routes/admin/system-health'
import { Route as AdminSupportRouteImport } from './routes/admin/support'
import { Route as AdminMonitoringRouteImport } from './routes/admin/monitoring'
import { Route as AdminFeatureFlagsRouteImport } from './routes/admin/feature-flags'
import { Route as AdminCrmRouteImport } from './routes/admin/crm'
import { Route as AdminClientsRouteImport } from './routes/admin/clients'
import { Route as AdminBillingRouteImport } from './routes/admin/billing'
import { Route as AdminAutomationViewRouteImport } from './routes/admin/automation-view'
import { Route as AdminApiLogsRouteImport } from './routes/admin/api-logs'
import { Route as AdminAnnouncementsRouteImport } from './routes/admin/announcements'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAiModelsRouteImport } from './routes/admin/ai-models'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedProvidersRouteImport } from './routes/_authenticated/providers'
import { Route as AuthenticatedPromptsRouteImport } from './routes/_authenticated/prompts'
import { Route as AuthenticatedProductsRouteImport } from './routes/_authenticated/products'
import { Route as AuthenticatedOrdersRouteImport } from './routes/_authenticated/orders'
import { Route as AuthenticatedLogsRouteImport } from './routes/_authenticated/logs'
import { Route as AuthenticatedImagesRouteImport } from './routes/_authenticated/images'
import { Route as AuthenticatedFbPostGeneratorRouteImport } from './routes/_authenticated/fb-post-generator'
import { Route as AuthenticatedFacebookRouteImport } from './routes/_authenticated/facebook'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChatsRouteImport } from './routes/_authenticated/chats'
import { Route as AuthenticatedBrandMemoryRouteImport } from './routes/_authenticated/brand-memory'
import { Route as AuthenticatedAutomationRouteImport } from './routes/_authenticated/automation'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedAiSettingsRouteImport } from './routes/_authenticated/ai-settings'
import { Route as ApiPublicWaWebhookRouteImport } from './routes/api/public/wa/webhook'
import { Route as ApiPublicFbWebhookRouteImport } from './routes/api/public/fb/webhook'
import { Route as ApiPublicFbOauthCallbackRouteImport } from './routes/api/public/fb/oauth.callback'

const OrderSuccessRoute = OrderSuccessRouteImport.update({
  id: '/order-success',
  path: '/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopIndexRoute = ShopIndexRouteImport.update({
  id: '/shop/',
  path: '/shop/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/shop/$slug',
  path: '/shop/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSlugRoute = CheckoutSlugRouteImport.update({
  id: '/checkout/$slug',
  path: '/checkout/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWhatsappRoute = AppWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProvidersRoute = AppProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOnboardingRoute = AppOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFacebookRoute = AppFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEcommerceRoute = AppEcommerceRouteImport.update({
  id: '/ecommerce',
  path: '/ecommerce',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatsRoute = AppChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppBrandMemoryRoute = AppBrandMemoryRouteImport.update({
  id: '/brand-memory',
  path: '/brand-memory',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAiSettingsRoute = AppAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AdminTenantsRoute = AdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSystemHealthRoute = AdminSystemHealthRouteImport.update({
  id: '/system-health',
  path: '/system-health',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSupportRoute = AdminSupportRouteImport.update({
  id: '/support',
  path: '/support',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminMonitoringRoute = AdminMonitoringRouteImport.update({
  id: '/monitoring',
  path: '/monitoring',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminFeatureFlagsRoute = AdminFeatureFlagsRouteImport.update({
  id: '/feature-flags',
  path: '/feature-flags',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminCrmRoute = AdminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminBillingRoute = AdminBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAutomationViewRoute = AdminAutomationViewRouteImport.update({
  id: '/automation-view',
  path: '/automation-view',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminApiLogsRoute = AdminApiLogsRouteImport.update({
  id: '/api-logs',
  path: '/api-logs',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnnouncementsRoute = AdminAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminAiModelsRoute = AdminAiModelsRouteImport.update({
  id: '/ai-models',
  path: '/ai-models',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProvidersRoute = AuthenticatedProvidersRouteImport.update({
  id: '/providers',
  path: '/providers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPromptsRoute = AuthenticatedPromptsRouteImport.update({
  id: '/prompts',
  path: '/prompts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedProductsRoute = AuthenticatedProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrdersRoute = AuthenticatedOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLogsRoute = AuthenticatedLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedImagesRoute = AuthenticatedImagesRouteImport.update({
  id: '/images',
  path: '/images',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFbPostGeneratorRoute =
  AuthenticatedFbPostGeneratorRouteImport.update({
    id: '/fb-post-generator',
    path: '/fb-post-generator',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacebookRoute = AuthenticatedFacebookRouteImport.update({
  id: '/facebook',
  path: '/facebook',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatsRoute = AuthenticatedChatsRouteImport.update({
  id: '/chats',
  path: '/chats',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBrandMemoryRoute =
  AuthenticatedBrandMemoryRouteImport.update({
    id: '/brand-memory',
    path: '/brand-memory',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutomationRoute = AuthenticatedAutomationRouteImport.update({
  id: '/automation',
  path: '/automation',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAiSettingsRoute = AuthenticatedAiSettingsRouteImport.update({
  id: '/ai-settings',
  path: '/ai-settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWaWebhookRoute = ApiPublicWaWebhookRouteImport.update({
  id: '/api/public/wa/webhook',
  path: '/api/public/wa/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbWebhookRoute = ApiPublicFbWebhookRouteImport.update({
  id: '/api/public/fb/webhook',
  path: '/api/public/fb/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFbOauthCallbackRoute =
  ApiPublicFbOauthCallbackRouteImport.update({
    id: '/api/public/fb/oauth/callback',
    path: '/api/public/fb/oauth/callback',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/order-success': typeof OrderSuccessRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/brand-memory': typeof AuthenticatedBrandMemoryRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/fb-post-generator': typeof AuthenticatedFbPostGeneratorRoute
  '/images': typeof AuthenticatedImagesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/automation-view': typeof AdminAutomationViewRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/ai-settings': typeof AppAiSettingsRoute
  '/app/brand-memory': typeof AppBrandMemoryRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/ecommerce': typeof AppEcommerceRoute
  '/app/facebook': typeof AppFacebookRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/api/public/fb/oauth/callback': typeof ApiPublicFbOauthCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/order-success': typeof OrderSuccessRoute
  '/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/automation': typeof AuthenticatedAutomationRoute
  '/brand-memory': typeof AuthenticatedBrandMemoryRoute
  '/chats': typeof AuthenticatedChatsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/facebook': typeof AuthenticatedFacebookRoute
  '/fb-post-generator': typeof AuthenticatedFbPostGeneratorRoute
  '/images': typeof AuthenticatedImagesRoute
  '/logs': typeof AuthenticatedLogsRoute
  '/orders': typeof AuthenticatedOrdersRoute
  '/products': typeof AuthenticatedProductsRoute
  '/prompts': typeof AuthenticatedPromptsRoute
  '/providers': typeof AuthenticatedProvidersRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/automation-view': typeof AdminAutomationViewRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/ai-settings': typeof AppAiSettingsRoute
  '/app/brand-memory': typeof AppBrandMemoryRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/ecommerce': typeof AppEcommerceRoute
  '/app/facebook': typeof AppFacebookRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/shop': typeof ShopIndexRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/api/public/fb/oauth/callback': typeof ApiPublicFbOauthCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/app': typeof AppRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/order-success': typeof OrderSuccessRoute
  '/_authenticated/ai-settings': typeof AuthenticatedAiSettingsRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/automation': typeof AuthenticatedAutomationRoute
  '/_authenticated/brand-memory': typeof AuthenticatedBrandMemoryRoute
  '/_authenticated/chats': typeof AuthenticatedChatsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/facebook': typeof AuthenticatedFacebookRoute
  '/_authenticated/fb-post-generator': typeof AuthenticatedFbPostGeneratorRoute
  '/_authenticated/images': typeof AuthenticatedImagesRoute
  '/_authenticated/logs': typeof AuthenticatedLogsRoute
  '/_authenticated/orders': typeof AuthenticatedOrdersRoute
  '/_authenticated/products': typeof AuthenticatedProductsRoute
  '/_authenticated/prompts': typeof AuthenticatedPromptsRoute
  '/_authenticated/providers': typeof AuthenticatedProvidersRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/admin/ai-models': typeof AdminAiModelsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/announcements': typeof AdminAnnouncementsRoute
  '/admin/api-logs': typeof AdminApiLogsRoute
  '/admin/automation-view': typeof AdminAutomationViewRoute
  '/admin/billing': typeof AdminBillingRoute
  '/admin/clients': typeof AdminClientsRoute
  '/admin/crm': typeof AdminCrmRoute
  '/admin/feature-flags': typeof AdminFeatureFlagsRoute
  '/admin/monitoring': typeof AdminMonitoringRoute
  '/admin/support': typeof AdminSupportRoute
  '/admin/system-health': typeof AdminSystemHealthRoute
  '/admin/tenants': typeof AdminTenantsRoute
  '/app/ai-settings': typeof AppAiSettingsRoute
  '/app/brand-memory': typeof AppBrandMemoryRoute
  '/app/chats': typeof AppChatsRoute
  '/app/dashboard': typeof AppDashboardRoute
  '/app/ecommerce': typeof AppEcommerceRoute
  '/app/facebook': typeof AppFacebookRoute
  '/app/onboarding': typeof AppOnboardingRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/products': typeof AppProductsRoute
  '/app/providers': typeof AppProvidersRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/whatsapp': typeof AppWhatsappRoute
  '/checkout/$slug': typeof CheckoutSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/shop/': typeof ShopIndexRoute
  '/api/public/fb/webhook': typeof ApiPublicFbWebhookRoute
  '/api/public/wa/webhook': typeof ApiPublicWaWebhookRoute
  '/api/public/fb/oauth/callback': typeof ApiPublicFbOauthCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/app'
    | '/auth'
    | '/order-success'
    | '/ai-settings'
    | '/analytics'
    | '/automation'
    | '/brand-memory'
    | '/chats'
    | '/dashboard'
    | '/facebook'
    | '/fb-post-generator'
    | '/images'
    | '/logs'
    | '/orders'
    | '/products'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api-logs'
    | '/admin/automation-view'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/feature-flags'
    | '/admin/monitoring'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/app/ai-settings'
    | '/app/brand-memory'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/ecommerce'
    | '/app/facebook'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/products'
    | '/app/providers'
    | '/app/settings'
    | '/app/whatsapp'
    | '/checkout/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/app/'
    | '/shop/'
    | '/api/public/fb/webhook'
    | '/api/public/wa/webhook'
    | '/api/public/fb/oauth/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/order-success'
    | '/ai-settings'
    | '/analytics'
    | '/automation'
    | '/brand-memory'
    | '/chats'
    | '/dashboard'
    | '/facebook'
    | '/fb-post-generator'
    | '/images'
    | '/logs'
    | '/orders'
    | '/products'
    | '/prompts'
    | '/providers'
    | '/settings'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api-logs'
    | '/admin/automation-view'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/feature-flags'
    | '/admin/monitoring'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/app/ai-settings'
    | '/app/brand-memory'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/ecommerce'
    | '/app/facebook'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/products'
    | '/app/providers'
    | '/app/settings'
    | '/app/whatsapp'
    | '/checkout/$slug'
    | '/shop/$slug'
    | '/admin'
    | '/app'
    | '/shop'
    | '/api/public/fb/webhook'
    | '/api/public/wa/webhook'
    | '/api/public/fb/oauth/callback'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/app'
    | '/auth'
    | '/order-success'
    | '/_authenticated/ai-settings'
    | '/_authenticated/analytics'
    | '/_authenticated/automation'
    | '/_authenticated/brand-memory'
    | '/_authenticated/chats'
    | '/_authenticated/dashboard'
    | '/_authenticated/facebook'
    | '/_authenticated/fb-post-generator'
    | '/_authenticated/images'
    | '/_authenticated/logs'
    | '/_authenticated/orders'
    | '/_authenticated/products'
    | '/_authenticated/prompts'
    | '/_authenticated/providers'
    | '/_authenticated/settings'
    | '/admin/ai-models'
    | '/admin/analytics'
    | '/admin/announcements'
    | '/admin/api-logs'
    | '/admin/automation-view'
    | '/admin/billing'
    | '/admin/clients'
    | '/admin/crm'
    | '/admin/feature-flags'
    | '/admin/monitoring'
    | '/admin/support'
    | '/admin/system-health'
    | '/admin/tenants'
    | '/app/ai-settings'
    | '/app/brand-memory'
    | '/app/chats'
    | '/app/dashboard'
    | '/app/ecommerce'
    | '/app/facebook'
    | '/app/onboarding'
    | '/app/orders'
    | '/app/products'
    | '/app/providers'
    | '/app/settings'
    | '/app/whatsapp'
    | '/checkout/$slug'
    | '/shop/$slug'
    | '/admin/'
    | '/app/'
    | '/shop/'
    | '/api/public/fb/webhook'
    | '/api/public/wa/webhook'
    | '/api/public/fb/oauth/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  OrderSuccessRoute: typeof OrderSuccessRoute
  CheckoutSlugRoute: typeof CheckoutSlugRoute
  ShopSlugRoute: typeof ShopSlugRoute
  ShopIndexRoute: typeof ShopIndexRoute
  ApiPublicFbWebhookRoute: typeof ApiPublicFbWebhookRoute
  ApiPublicWaWebhookRoute: typeof ApiPublicWaWebhookRoute
  ApiPublicFbOauthCallbackRoute: typeof ApiPublicFbOauthCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/order-success': {
      id: '/order-success'
      path: '/order-success'
      fullPath: '/order-success'
      preLoaderRoute: typeof OrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/': {
      id: '/shop/'
      path: '/shop'
      fullPath: '/shop/'
      preLoaderRoute: typeof ShopIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/shop/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/$slug': {
      id: '/checkout/$slug'
      path: '/checkout/$slug'
      fullPath: '/checkout/$slug'
      preLoaderRoute: typeof CheckoutSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/whatsapp': {
      id: '/app/whatsapp'
      path: '/whatsapp'
      fullPath: '/app/whatsapp'
      preLoaderRoute: typeof AppWhatsappRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/providers': {
      id: '/app/providers'
      path: '/providers'
      fullPath: '/app/providers'
      preLoaderRoute: typeof AppProvidersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/onboarding': {
      id: '/app/onboarding'
      path: '/onboarding'
      fullPath: '/app/onboarding'
      preLoaderRoute: typeof AppOnboardingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/facebook': {
      id: '/app/facebook'
      path: '/facebook'
      fullPath: '/app/facebook'
      preLoaderRoute: typeof AppFacebookRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ecommerce': {
      id: '/app/ecommerce'
      path: '/ecommerce'
      fullPath: '/app/ecommerce'
      preLoaderRoute: typeof AppEcommerceRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/dashboard': {
      id: '/app/dashboard'
      path: '/dashboard'
      fullPath: '/app/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chats': {
      id: '/app/chats'
      path: '/chats'
      fullPath: '/app/chats'
      preLoaderRoute: typeof AppChatsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/brand-memory': {
      id: '/app/brand-memory'
      path: '/brand-memory'
      fullPath: '/app/brand-memory'
      preLoaderRoute: typeof AppBrandMemoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/ai-settings': {
      id: '/app/ai-settings'
      path: '/ai-settings'
      fullPath: '/app/ai-settings'
      preLoaderRoute: typeof AppAiSettingsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/admin/tenants': {
      id: '/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AdminTenantsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/system-health': {
      id: '/admin/system-health'
      path: '/system-health'
      fullPath: '/admin/system-health'
      preLoaderRoute: typeof AdminSystemHealthRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/support': {
      id: '/admin/support'
      path: '/support'
      fullPath: '/admin/support'
      preLoaderRoute: typeof AdminSupportRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/monitoring': {
      id: '/admin/monitoring'
      path: '/monitoring'
      fullPath: '/admin/monitoring'
      preLoaderRoute: typeof AdminMonitoringRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/feature-flags': {
      id: '/admin/feature-flags'
      path: '/feature-flags'
      fullPath: '/admin/feature-flags'
      preLoaderRoute: typeof AdminFeatureFlagsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/crm': {
      id: '/admin/crm'
      path: '/crm'
      fullPath: '/admin/crm'
      preLoaderRoute: typeof AdminCrmRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/clients': {
      id: '/admin/clients'
      path: '/clients'
      fullPath: '/admin/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/billing': {
      id: '/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AdminBillingRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/automation-view': {
      id: '/admin/automation-view'
      path: '/automation-view'
      fullPath: '/admin/automation-view'
      preLoaderRoute: typeof AdminAutomationViewRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/api-logs': {
      id: '/admin/api-logs'
      path: '/api-logs'
      fullPath: '/admin/api-logs'
      preLoaderRoute: typeof AdminApiLogsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/announcements': {
      id: '/admin/announcements'
      path: '/announcements'
      fullPath: '/admin/announcements'
      preLoaderRoute: typeof AdminAnnouncementsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/ai-models': {
      id: '/admin/ai-models'
      path: '/ai-models'
      fullPath: '/admin/ai-models'
      preLoaderRoute: typeof AdminAiModelsRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/providers': {
      id: '/_authenticated/providers'
      path: '/providers'
      fullPath: '/providers'
      preLoaderRoute: typeof AuthenticatedProvidersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prompts': {
      id: '/_authenticated/prompts'
      path: '/prompts'
      fullPath: '/prompts'
      preLoaderRoute: typeof AuthenticatedPromptsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/products': {
      id: '/_authenticated/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof AuthenticatedProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orders': {
      id: '/_authenticated/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof AuthenticatedOrdersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/logs': {
      id: '/_authenticated/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthenticatedLogsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/images': {
      id: '/_authenticated/images'
      path: '/images'
      fullPath: '/images'
      preLoaderRoute: typeof AuthenticatedImagesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/fb-post-generator': {
      id: '/_authenticated/fb-post-generator'
      path: '/fb-post-generator'
      fullPath: '/fb-post-generator'
      preLoaderRoute: typeof AuthenticatedFbPostGeneratorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facebook': {
      id: '/_authenticated/facebook'
      path: '/facebook'
      fullPath: '/facebook'
      preLoaderRoute: typeof AuthenticatedFacebookRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chats': {
      id: '/_authenticated/chats'
      path: '/chats'
      fullPath: '/chats'
      preLoaderRoute: typeof AuthenticatedChatsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/brand-memory': {
      id: '/_authenticated/brand-memory'
      path: '/brand-memory'
      fullPath: '/brand-memory'
      preLoaderRoute: typeof AuthenticatedBrandMemoryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/automation': {
      id: '/_authenticated/automation'
      path: '/automation'
      fullPath: '/automation'
      preLoaderRoute: typeof AuthenticatedAutomationRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-settings': {
      id: '/_authenticated/ai-settings'
      path: '/ai-settings'
      fullPath: '/ai-settings'
      preLoaderRoute: typeof AuthenticatedAiSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/wa/webhook': {
      id: '/api/public/wa/webhook'
      path: '/api/public/wa/webhook'
      fullPath: '/api/public/wa/webhook'
      preLoaderRoute: typeof ApiPublicWaWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb/webhook': {
      id: '/api/public/fb/webhook'
      path: '/api/public/fb/webhook'
      fullPath: '/api/public/fb/webhook'
      preLoaderRoute: typeof ApiPublicFbWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/fb/oauth/callback': {
      id: '/api/public/fb/oauth/callback'
      path: '/api/public/fb/oauth/callback'
      fullPath: '/api/public/fb/oauth/callback'
      preLoaderRoute: typeof ApiPublicFbOauthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAiSettingsRoute: typeof AuthenticatedAiSettingsRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedAutomationRoute: typeof AuthenticatedAutomationRoute
  AuthenticatedBrandMemoryRoute: typeof AuthenticatedBrandMemoryRoute
  AuthenticatedChatsRoute: typeof AuthenticatedChatsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFacebookRoute: typeof AuthenticatedFacebookRoute
  AuthenticatedFbPostGeneratorRoute: typeof AuthenticatedFbPostGeneratorRoute
  AuthenticatedImagesRoute: typeof AuthenticatedImagesRoute
  AuthenticatedLogsRoute: typeof AuthenticatedLogsRoute
  AuthenticatedOrdersRoute: typeof AuthenticatedOrdersRoute
  AuthenticatedProductsRoute: typeof AuthenticatedProductsRoute
  AuthenticatedPromptsRoute: typeof AuthenticatedPromptsRoute
  AuthenticatedProvidersRoute: typeof AuthenticatedProvidersRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAiSettingsRoute: AuthenticatedAiSettingsRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedAutomationRoute: AuthenticatedAutomationRoute,
  AuthenticatedBrandMemoryRoute: AuthenticatedBrandMemoryRoute,
  AuthenticatedChatsRoute: AuthenticatedChatsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFacebookRoute: AuthenticatedFacebookRoute,
  AuthenticatedFbPostGeneratorRoute: AuthenticatedFbPostGeneratorRoute,
  AuthenticatedImagesRoute: AuthenticatedImagesRoute,
  AuthenticatedLogsRoute: AuthenticatedLogsRoute,
  AuthenticatedOrdersRoute: AuthenticatedOrdersRoute,
  AuthenticatedProductsRoute: AuthenticatedProductsRoute,
  AuthenticatedPromptsRoute: AuthenticatedPromptsRoute,
  AuthenticatedProvidersRoute: AuthenticatedProvidersRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminAiModelsRoute: typeof AdminAiModelsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAnnouncementsRoute: typeof AdminAnnouncementsRoute
  AdminApiLogsRoute: typeof AdminApiLogsRoute
  AdminAutomationViewRoute: typeof AdminAutomationViewRoute
  AdminBillingRoute: typeof AdminBillingRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCrmRoute: typeof AdminCrmRoute
  AdminFeatureFlagsRoute: typeof AdminFeatureFlagsRoute
  AdminMonitoringRoute: typeof AdminMonitoringRoute
  AdminSupportRoute: typeof AdminSupportRoute
  AdminSystemHealthRoute: typeof AdminSystemHealthRoute
  AdminTenantsRoute: typeof AdminTenantsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminAiModelsRoute: AdminAiModelsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAnnouncementsRoute: AdminAnnouncementsRoute,
  AdminApiLogsRoute: AdminApiLogsRoute,
  AdminAutomationViewRoute: AdminAutomationViewRoute,
  AdminBillingRoute: AdminBillingRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCrmRoute: AdminCrmRoute,
  AdminFeatureFlagsRoute: AdminFeatureFlagsRoute,
  AdminMonitoringRoute: AdminMonitoringRoute,
  AdminSupportRoute: AdminSupportRoute,
  AdminSystemHealthRoute: AdminSystemHealthRoute,
  AdminTenantsRoute: AdminTenantsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface AppRouteRouteChildren {
  AppAiSettingsRoute: typeof AppAiSettingsRoute
  AppBrandMemoryRoute: typeof AppBrandMemoryRoute
  AppChatsRoute: typeof AppChatsRoute
  AppDashboardRoute: typeof AppDashboardRoute
  AppEcommerceRoute: typeof AppEcommerceRoute
  AppFacebookRoute: typeof AppFacebookRoute
  AppOnboardingRoute: typeof AppOnboardingRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProductsRoute: typeof AppProductsRoute
  AppProvidersRoute: typeof AppProvidersRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppWhatsappRoute: typeof AppWhatsappRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppAiSettingsRoute: AppAiSettingsRoute,
  AppBrandMemoryRoute: AppBrandMemoryRoute,
  AppChatsRoute: AppChatsRoute,
  AppDashboardRoute: AppDashboardRoute,
  AppEcommerceRoute: AppEcommerceRoute,
  AppFacebookRoute: AppFacebookRoute,
  AppOnboardingRoute: AppOnboardingRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProductsRoute: AppProductsRoute,
  AppProvidersRoute: AppProvidersRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppWhatsappRoute: AppWhatsappRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  OrderSuccessRoute: OrderSuccessRoute,
  CheckoutSlugRoute: CheckoutSlugRoute,
  ShopSlugRoute: ShopSlugRoute,
  ShopIndexRoute: ShopIndexRoute,
  ApiPublicFbWebhookRoute: ApiPublicFbWebhookRoute,
  ApiPublicWaWebhookRoute: ApiPublicWaWebhookRoute,
  ApiPublicFbOauthCallbackRoute: ApiPublicFbOauthCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
